/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import estructuras.ArbolAvl;
import estructuras.Nodo;
import estructuras.NodoAVL;
import estructuras.NodoSimpleB;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.net.MalformedURLException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import manejadores.manejadorLibros;
import objetos.Libro;
import objetos.SesionActiva;
import org.json.JSONObject;
import org.json.*;

/**
 *
 * @author USUARIO
 */
public class librosUI extends javax.swing.JFrame {

    /**
     * Creates new form librosUI
     */
    public librosUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ltitulo = new javax.swing.JLabel();
        lisbn = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lanio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ledicion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        leditorial = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lidioma = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lautor = new javax.swing.JLabel();
        lcategoria = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lpropietario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Titulo");

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Nombre");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 80, 30));

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 220, 30));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("ISBN");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 60, 30));

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("Categoria");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 90, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Nombre", "Categoria", "Propietario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 199, 580, 340));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Titulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, -1, -1));

        ltitulo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ltitulo.setForeground(new java.awt.Color(0, 0, 0));
        ltitulo.setText("***********************************");
        getContentPane().add(ltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 240, 20));

        lisbn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lisbn.setForeground(new java.awt.Color(0, 0, 0));
        lisbn.setText("*************************************");
        getContentPane().add(lisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 240, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ISBN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Año");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));

        lanio.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lanio.setForeground(new java.awt.Color(0, 0, 0));
        lanio.setText("*************************************");
        getContentPane().add(lanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 240, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Edicion");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        ledicion.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        ledicion.setForeground(new java.awt.Color(0, 0, 0));
        ledicion.setText("*************************************");
        getContentPane().add(ledicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 240, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Editorial");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        leditorial.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        leditorial.setForeground(new java.awt.Color(0, 0, 0));
        leditorial.setText("*************************************");
        getContentPane().add(leditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 240, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Idioma");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, -1));

        lidioma.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lidioma.setForeground(new java.awt.Color(0, 0, 0));
        lidioma.setText("************************************");
        getContentPane().add(lidioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 250, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Categoria");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, -1));

        lautor.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lautor.setForeground(new java.awt.Color(0, 0, 0));
        lautor.setText("************************************");
        getContentPane().add(lautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 240, -1));

        lcategoria.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lcategoria.setForeground(new java.awt.Color(0, 0, 0));
        lcategoria.setText("************************************");
        getContentPane().add(lcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 240, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Propietario");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Autor");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        lpropietario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lpropietario.setForeground(new java.awt.Color(0, 0, 0));
        lpropietario.setText("************************************");
        getContentPane().add(lpropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 240, -1));

        jButton1.setText("Graficar AVL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        jButton8.setText("Graficar B");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, -1, -1));

        jButton2.setText("Eliminar Libro");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, -1, -1));

        jButton6.setText("Volver al Menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 40, -1, -1));

        jButton9.setText("Post Orden");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 80, 110, -1));

        jButton10.setText("In Orden");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 100, -1));

        jButton11.setText("Pre Orden");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/libreria.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 20, 980, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTable1.setModel(new DefaultTableModel(null, new String[]{"ISBN", "Nombre", "Categoria", "Propietario"}));

        manejadorLibros m = new manejadorLibros();
        m.libro_nombre(jTextField1.getText());
        NodoSimpleB aux = new NodoSimpleB();
        aux = ArbolAvl.resultado_busqueda.inicio.getSiguiente();
        if (aux != null) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            while (aux != null) {
                Vector row = new Vector();
                row.add(aux.getValor().getIsbn());
                row.add(aux.getValor().getTitulo());
                row.add(aux.getValor().getCategoria());
                row.add(aux.getValor().getPropietario());
                model.addRow(row);
                aux = aux.getSiguiente();
            }
            JOptionPane.showMessageDialog(null, "Mostrando coincidencias");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron coincidencias");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        jTable1.setModel(new DefaultTableModel(null, new String[]{"ISBN", "Nombre", "Categoria", "Propietario"}));
        manejadorLibros m = new manejadorLibros();
        m.libro_isbn(jTextField1.getText());
        NodoSimpleB aux = new NodoSimpleB();
        aux = ArbolAvl.resultado_busqueda.inicio.getSiguiente();
        if (aux != null) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            while (aux != null) {
                Vector row = new Vector();
                row.add(aux.getValor().getIsbn());
                row.add(aux.getValor().getTitulo());
                row.add(aux.getValor().getCategoria());
                row.add(aux.getValor().getPropietario());
                model.addRow(row);
                aux = aux.getSiguiente();
            }
            JOptionPane.showMessageDialog(null, "Mostrando coincidencias");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontraron coincidencias");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        jTable1.setModel(new DefaultTableModel(null, new String[]{"ISBN", "Nombre", "Categoria", "Propietario"}));
        manejadorLibros m = new manejadorLibros();
        m.busqueda_categoria(jTextField1.getText());
        NodoSimpleB aux = new NodoSimpleB();
        try {
            aux = ArbolAvl.resultado_busqueda.inicio.getSiguiente();
            if (aux != null) {
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

                while (aux != null) {
                    Vector row = new Vector();
                    row.add(aux.getValor().getIsbn());
                    row.add(aux.getValor().getTitulo());
                    row.add(aux.getValor().getCategoria());
                    row.add(aux.getValor().getPropietario());
                    model.addRow(row);
                    aux = aux.getSiguiente();
                }
                JOptionPane.showMessageDialog(null, "Mostrando coincidencias");
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron coincidencias");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se encontraron coincidencias");
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            manejadorLibros m = new manejadorLibros();
            m.graficalAVL();
            JOptionPane.showMessageDialog(null, "Grafica generada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error generando AVL");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            NodoAVL aux2 = SesionActiva.libros.buscar_categoria(jTextField1.getText());
            aux2.getLibros().generarDot();
            JOptionPane.showMessageDialog(null, "Grafica generada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error generando Arbol B");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String isbn = model.getValueAt(index, 0).toString();
        manejadorLibros m = new manejadorLibros();
        m.libro_isbn(isbn);
        SesionActiva.libros.buscar_isbn(isbn);
        NodoSimpleB aux = ArbolAvl.resultado_busqueda.inicio.getSiguiente();
        ltitulo.setText(aux.getValor().getTitulo());
        lisbn.setText(aux.getValor().getIsbn());
        lanio.setText(aux.getValor().getAnio());
        ledicion.setText(aux.getValor().getEdicion());
        leditorial.setText(aux.getValor().getEditorial());
        lidioma.setText(aux.getValor().getIdioma());
        lautor.setText(aux.getValor().getAutor());
        lcategoria.setText(aux.getValor().getCategoria());
        lpropietario.setText(aux.getValor().getPropietario() + "");
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            NodoSimpleB aux = ArbolAvl.resultado_busqueda.inicio.getSiguiente();
            manejadorLibros m = new manejadorLibros();
            if (m.eliminar_libro(aux.getValor().getIsbn())) {
                JOptionPane.showMessageDialog(null, "Libro Eliminado");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        usuariosUI u = new usuariosUI();
        u.show();
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        String ruta = "preorden.dot";
        String rutapng = "preorden.png";
        try {
            File file = new File(ruta);
            if (!file.exists()) {
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(SesionActiva.libros.dot_pre());
            bw.close();
            ProcessBuilder pbuilder;
            pbuilder = new ProcessBuilder("dot", "-Tpng", "-o", rutapng, ruta);
            pbuilder.redirectErrorStream(true);
            pbuilder.start();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String ruta = "inorden.dot";
        String rutapng = "inorden.png";
        try {
            File file = new File(ruta);
            if (!file.exists()) {
                file.createNewFile();
            }
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(SesionActiva.libros.dot_in());
            bw.close();
            ProcessBuilder pbuilder;
            pbuilder = new ProcessBuilder("dot", "-Tpng", "-o", rutapng, ruta);
            pbuilder.redirectErrorStream(true);
            pbuilder.start();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String ruta = "postorden.dot";
        String rutapng = "postorden.png";
        try {
            File file = new File(ruta);
            FileWriter fw = new FileWriter(file);
            fw.write(SesionActiva.libros.dot_pos());
            fw.close();
            Runtime rt = Runtime.getRuntime();
            rt.exec("dot -Tpng " + ruta + " -o " + rutapng);
  /*          ProcessBuilder pbuilder;
            pbuilder = new ProcessBuilder("dot", "-Tpng", "-o", rutapng, ruta);
            pbuilder.redirectErrorStream(true);
            pbuilder.start();*/
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(librosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(librosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(librosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(librosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new librosUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lanio;
    private javax.swing.JLabel lautor;
    private javax.swing.JLabel lcategoria;
    private javax.swing.JLabel ledicion;
    private javax.swing.JLabel leditorial;
    private javax.swing.JLabel lidioma;
    private javax.swing.JLabel lisbn;
    private javax.swing.JLabel lpropietario;
    private javax.swing.JLabel ltitulo;
    // End of variables declaration//GEN-END:variables
}
