/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import estructuras.ArbolAvl;
import estructuras.TablaDispersa;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import manejadores.manejadorUsuarios;
import objetos.SesionActiva;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author USUARIO
 */
public class perfilUsuario extends javax.swing.JFrame {

    /**
     * Creates new form perfilUsuario
     */
    public perfilUsuario() {
        initComponents();
        carnet.setText(SesionActiva.usuario_sesion.getCarnet() + "");
        nombre.setText(SesionActiva.usuario_sesion.getNombre());
        apellido.setText(SesionActiva.usuario_sesion.getApellido());
        carrera.setText(SesionActiva.usuario_sesion.getCarrera());
        contra.setText(SesionActiva.usuario_sesion.getPassword());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        carrera = new javax.swing.JTextField();
        contra = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        carnet = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Editar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 120, -1));

        jButton2.setText("Eliminar Cuenta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 340, 120, -1));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 200, -1));
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 200, -1));
        getContentPane().add(carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 200, -1));
        getContentPane().add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 200, -1));

        jButton3.setText("Carga Masiva");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 120, -1));
        getContentPane().add(carnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 200, -1));

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("Crear Usuario");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 120, -1));

        jButton5.setText("Reporte");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, -1));

        jButton6.setText("Cerrar Sesion");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 120, -1));

        jButton7.setText("Volver al Menu");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\ui\\user.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        manejadorUsuarios manejador = new manejadorUsuarios();
        String n = nombre.getText();
        String a = apellido.getText();
        String c = carrera.getText();
        String con = contra.getText();

        if (n.compareTo("") == 0) {
            n = SesionActiva.usuario_sesion.getNombre();
        }
        if (a.compareTo("") == 0) {
            a = SesionActiva.usuario_sesion.getApellido();
        }
        if (c.compareTo("") == 0) {
            c = SesionActiva.usuario_sesion.getCarrera();
        }
        if (con.compareTo("") == 0) {
            con = SesionActiva.usuario_sesion.getPassword();
        }

        if (manejador.editar(SesionActiva.usuario_sesion.getCarnet(), n, a, c, con)) {
            JOptionPane.showMessageDialog(null, "Datos Actualizados");
        } else {
            JOptionPane.showMessageDialog(null, "Verifique sus datos");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        manejadorUsuarios manejador = new manejadorUsuarios();
        if (manejador.eliminar(SesionActiva.usuario_sesion.getCarnet())) {
            JOptionPane.showMessageDialog(null, "Cuenta Eliminada Correctamente");
            this.dispose();
            main m = new main();
            m.show();
        } else {
            JOptionPane.showMessageDialog(null, "Error en la eliminacion");

        }
        //redirigir al login
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        manejadorUsuarios manejador = new manejadorUsuarios();
        manejador.carga_masiva();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        manejadorUsuarios manejador = new manejadorUsuarios();
        String car = carnet.getText();
        String n = nombre.getText();
        String a = apellido.getText();
        String c = carrera.getText();
        String con = contra.getText();

        if (n.compareTo("") != 0 && a.compareTo("") != 0 && c.compareTo("") != 0 && car.compareTo("") != 0 && con.compareTo("") != 0) {

            try {
                int ca = Integer.parseInt(car);
                if (manejador.registrar(ca, n, a, c, con)) {
                    JOptionPane.showMessageDialog(null, "Registro exitoso");
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario ya existe");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Verifique sus datos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        manejadorUsuarios m = new manejadorUsuarios();
        m.graficar();
        String ruta = "hash.dot";
        String rutapng = "hash.png";
        SesionActiva.libros.generarDot();
        try {
            ProcessBuilder pbuilder;
            pbuilder = new ProcessBuilder("dot", "-Tpng", "-o", rutapng, ruta);
            pbuilder.redirectErrorStream(true);
            pbuilder.start();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        usuariosUI u = new usuariosUI();
        u.show();
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        main m = new main();
        m.show();
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perfilUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField apellido;
    private static javax.swing.JTextField carnet;
    private static javax.swing.JTextField carrera;
    private static javax.swing.JTextField contra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
